# Generated by Django 5.1.1 on 2024-09-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='formis_payment_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='payment_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='payment_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='payment_completed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='payment_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='vendor_payment_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
