# Generated by Django 5.1.1 on 2024-09-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_registration', '0002_eventbooking_formis_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbooking',
            name='payment_amount',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='payment_link',
            field=models.URLField(),
        ),
    ]
