# Generated by Django 5.1.1 on 2024-09-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_registration', '0003_alter_eventbooking_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbooking',
            name='address',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='eventbooking',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
